version: '3.8'

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.secret
  nc_mysql_password:
    file: ./secrets/nc_mysql_password.secret
  nc_admin_user:
    file: ./secrets/nc_admin_user.secret
  nc_admin_password:
    file: ./secrets/nc_admin_password.secret

services:
  db:
    image: mariadb:latest
    container_name: nextcloud-db
    volumes:
      - ./nextcloud-db-data:/var/lib/mysql
    networks:
      - db
    restart: always
    secrets: 
      - mysql_root_password
      - nc_mysql_password
    environment:
      - TZ=$TZ
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_DATABASE=db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD_FILE=/run/secrets/nc_mysql_password

  redis:
    image: redis:latest
    restart: always
    networks:
      - db
      - nc
    volumes:
      - ./redis:/var/lib/redis

  nextcloud:
    depends_on:
      - redis
      - db
    image: nextcloud:stable 
    container_name: nextcloud
    ports:
      - 8585:80
    secrets: 
      - nc_mysql_password
      - nc_admin_user
      - nc_admin_password
    volumes:
      - ./files:/var/www/html
    networks:
      - nc
      - db
    restart: always
#    labels:  # use labels only if on the same VM as Traefik (same Docker host)
      #- "traefik.enable=true"
      #- "traefik.docker.network=proxy"
      #- "traefik.http.routers.nextcloud-secure.entrypoints=websecure"
      #- "traefik.http.routers.nextcloud-secure.rule=Host(`cloud.yourdomain`)"
      #- "traefik.http.routers.nextcloud-secure.service=nextcloud-service"
      #- "traefik.http.services.nextcloud-service.loadbalancer.server.port=80"
    environment:
      - REDIS_HOST=redis
      - MYSQL_HOST=db:3306
      - MYSQL_DATABASE=db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD_FILE=/run/secrets/nc_mysql_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nc_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nc_admin_user
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.$DOMAINNAME $LOCALIP # space separated list

  ## Collabora - Document Server
  # Connect NextCloud to Collabora app with: https://office.DOMAINNAME
  # Admin console at https://<office-domain>/loleaflet/dist/admin/admin.html
  code:
    container_name: office
    image: collabora/code:latest
    restart: always
    networks:
      - nc
    ports:
      - 9980:9980
#    security_opt:
#      - no-new-privileges:true
    cap_add:
      - MKNOD
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - username=$MY_USERNAME
      - password=$MY_PASSWORD
      - domain=office.$DOMAINNAME #$MY_OFFICE_DOMAIN #<your-NEXTCLOUD-dot-escaped-domain>
      - VIRTUAL_HOST=office.$DOMAINNAME
      - LETSENCRYPT_HOST=office.$DOMAINNAME
#      - server_name=office.$DOMAINNAME
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true

#    labels:
#      - "traefik.enable=true"
#      ## HTTP Routers
#      - "traefik.http.routers.office-rtr.entrypoints=https"
#      - "traefik.http.routers.office-rtr.rule=Host(`office.$DOMAINNAME`)"
#      ## Middlewares
#      - "traefik.http.routers.office-rtr.middlewares=secure-headers@file"
#      ## HTTP Services
#      - "traefik.http.routers.office-rtr.service=office-svc"
#      - "traefik.http.services.office-svc.loadbalancer.server.port=9980"

networks:
  db:
    external: true
  nc:
    external: true
