version: '3.8'

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.secret
  nc_mysql_password:
    file: ./secrets/nc_mysql_password.secret
  nc_admin_user:
    file: ./nc_admin_user.secret
  nc_admin_password:
    file: ./nc_admin_password.secret

services:
  db:
    image: mariadb:latest
    container_name: nextcloud-db
    volumes:
      - nextcloud-db-data:/var/lib/mysql
    networks:
      - db
    restart: always
    secrets: 
      - mysql_root_password
      - nc_mysql_password
    environment:
      - TZ=Germany/Berlin
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_DATABASE=db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD_FILE=/run/secrets/nc_mysql_password

  redis:
    image: redis:latest
    restart: always
    networks:
      - db
      - nc
    volumes:
      - redis:/var/lib/redis

  nextcloud:
    depends_on:
      - redis
      - db
    image: nextcloud:stable 
    container_name: nextcloud
    secrets: 
      - nc_mysql_password
      - nc_admin_user
      - nc_admin_password
    volumes:
      - ./files:/var/www/html
    networks:
      - nc
      - db
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.nextcloud-secure.entrypoints=websecure"
      - "traefik.http.routers.nextcloud-secure.rule=Host(`cloud.yourdomain`)"
      - "traefik.http.routers.nextcloud-secure.service=nextcloud-service"
      - "traefik.http.services.nextcloud-service.loadbalancer.server.port=80"
    environment:
      - REDIS_HOST=redis
      - MYSQL_HOST=db:3306
      - MYSQL_DATABASE=db
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD_FILE=/run/secrets/nc_mysql_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nc_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nc_admin_user

networks:
  db:
    external: true
  nc:
    external: true
    
volumes:
  nextcloud-db-data:
    name: nextcloud-db-data
  redis:
    name: nextcloud-redis
